<script src="{{asset('front/js/jquery.js')}}"></script>
    <script src="{{asset('front/js/bootstrap.bundle.js')}}"></script>
    <!-- <script src="{{asset('front/js/card.js')}}"></script> -->
    <script src="{{asset('front/js/counterup2.js')}}"></script>
    <!-- <script src="{{asset('front/js/noise.js')}}"></script> -->
    <script src="{{asset('front/js/noframework.waypoints.js')}}"></script>
    <!-- <script src="{{asset('front/js/odometer.js')}}"></script>
    <script src="{{asset('front/js/prism.js')}}"></script>
    <script src="{{asset('front/js/simplebar.js')}}"></script> -->
    <script src="{{asset('front/js/swiper-bundle.js')}}"></script>
    <!-- <script src="{{asset('front/js/jquery.easing.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/jquery.validate.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/jquery.smartWizard.js')}}"></script> -->
    <script src="{{asset('front/js/feather.js')}}"></script>
    <script src="{{asset('front/js/aos.js')}}"></script>
    <script src="{{asset('front/js/typed.js')}}"></script>
    <script src="{{asset('front/js/jquery.magnific-popup.js')}}"></script>
    <script src="{{asset('front/js/cookieconsent.js')}}"></script>
    <script src="{{asset('front/js/jquery.animatebar.js')}}"></script>
    <script src="{{asset('front/js/common.js')}}"></script>
    <!-- <script src="{{asset('front/js/forms.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/stripe-bubbles.js')}}"></script> -->
    <script src="{{asset('front/js/stripe-menu.js')}}"></script>
    <!-- <script src="{{asset('front/js/credit-card.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/pricing.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/shop.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/svg.js')}}"></script> -->
    <script src="{{asset('front/js/site.js')}}"></script>
    <!-- <script src="{{asset('front/js/wizards.js')}}"></script> -->
    <!-- <script src="{{asset('front/js/cookie-consent-util.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-themes.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-custom-css.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-informational.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-opt-out.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-opt-in.js')}}"></script>
    <script src="{{asset('front/js/cookie-consent-location.js')}}"></script> -->
    <script src="{{asset('front/js/demo.js')}}"></script>
